# Movie.create!([
#   {title: "The Shawshank Redemption", year: "1994", director: "Hane, Bogisich and Nicolas", image: "https://ia.media-imdb.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg", genre: "Drama", description: "Qui dolorem et ad voluptatibus consequatur eveniet. Voluptatem voluptatem qui. Velit autem minus. Eaque reiciendis dolorum fuga sint voluptatem dolorem aperiam. Recusandae molestias nisi perspiciatis laboriosam quia temporibus est. Molestiae dolore voluptatem.", rating: "3", quote: "Fasten your seatbelts. It's going to be a bumpy night."},
#   {title: "12 Angry Men", year: "1957", director: "Bogisich LLC", image: "https://ia.media-imdb.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SY1000_CR0,0,649,1000_AL_.jpg", genre: "Narrative nonfiction", description: "Ea nobis quos rem natus et iure omnis. Aut est velit culpa. Eligendi optio mollitia tempora ea.", rating: "7", quote: "Fasten your seatbelts. It's going to be a bumpy night."},
#   {title: "The GodFather", year: "1972", director: "Ledner, Fadel and White", image: "https://ia.media-imdb.com/images/M/MV5BY2Q2NzQ3ZDUtNWU5OC00Yjc0LThlYmEtNWM3NTFmM2JiY2VhXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,700,1000_AL_.jpg", genre: "Drama", description: "Consequatur et quisquam sed. Qui voluptas similique ex odio sapiente et sunt. Atque placeat possimus beatae similique. Enim ullam omnis voluptatum saepe. Molestias at eos commodi voluptatem.", rating: "5", quote: "Frankly, my dear, I don’t give a damn."},
#   {title: "The Dark Knight", year: "2008", director: "Runolfsson Group", image: "https://ia.media-imdb.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SY1000_CR0,0,675,1000_AL_.jpg", genre: "Narrative nonfiction", description: "Ut ut quos sit harum nulla itaque quis. Et dolorem aliquam vel nihil velit. Consequuntur cum dignissimos. Et quo quidem aut minima modi delectus quo. Ut voluptatem nihil eveniet qui nulla et. Magnam in qui itaque maxime. Et suscipit consectetur sunt voluptas.", rating: "5", quote: "Frankly, my dear, I don’t give a damn."},
#   {title: "Fight Club", year: "1999", director: "Ullrich and Sons", image: "https://ia.media-imdb.com/images/M/MV5BMzFjMWNhYzQtYTIxNC00ZWQ1LThiOTItNWQyZmMxNDYyMjA5XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,675,1000_AL_.jpg", genre: "Legend", description: "Ducimus et id aliquam accusamus ipsum illum quasi. Veritatis dolores atque. Sit iste odio quod tempora exercitationem sed amet. Eveniet omnis dolores in aspernatur laborum quia. Et delectus sapiente consequatur aut.", rating: "6", quote: "I love the smell of napalm in the morning."},
#   {title: "Intersetllar", year: "2014", director: "Dare-Keebler", image: "https://ia.media-imdb.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SY1000_SX675_AL_.jpg", genre: "Biography/Autobiography", description: "Quo nobis laboriosam sed qui. Qui et sit id dignissimos fugit. Ducimus pariatur reiciendis.", rating: "1", quote: "Go ahead, make my day."},
#   {title: "The Departed", year: "2006", director: "Ankunding, Lehner and Paucek", image: "https://ia.media-imdb.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_.jpg", genre: "Western", description: "Natus libero officiis corrupti. Magnam expedita autem nulla suscipit dolores. Necessitatibus quaerat amet nam deserunt esse ut.", rating: "3", quote: "I love the smell of napalm in the morning."},
#   {title: "Inception", year: "2010", director: "Strosin-Heidenreich", image: "https://ia.media-imdb.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SY1000_CR0,0,675,1000_AL_.jpg", genre: "Crime/Detective", description: "In laboriosam enim quibusdam. Vel odit sunt minima. Ea eum similique sit. Deleniti est dignissimos similique. Soluta error adipisci repellat. Culpa illo quis voluptatem.", rating: "5", quote: "Go ahead, make my day."},
#   {title: "Back to the Future", year: "1985", director: "Heathcote Group", image: "https://ia.media-imdb.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SY1000_CR0,0,643,1000_AL_.jpg", genre: "Realistic fiction", description: "In aut ut est libero. Odio qui non voluptas nihil. Sequi amet molestiae incidunt ullam. Animi id nesciunt autem sequi unde. Dolore non voluptas error. Dolores sed unde voluptatem.", rating: "4", quote: "All right, Mr. DeMille, I'm ready for my closeup."},
#   {title: "Pulp Fiction", year: "1994", director: "Legros-Reichert", image: "https://ia.media-imdb.com/images/M/MV5BMTkxMTA5OTAzMl5BMl5BanBnXkFtZTgwNjA5MDc3NjE@._V1_SY1000_CR0,0,673,1000_AL_.jpg", genre: "Textbook", description: "Labore natus veritatis quis dolorem praesentium. Possimus id mollitia sunt nulla accusamus ad velit. Et nihil quas maxime.", rating: "9", quote: "Go ahead, make my day."},
#   {title: "The Matrix", year: "1999", director: "Lakin and Sons", image: "https://ia.media-imdb.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY1000_CR0,0,665,1000_AL_.jpg", genre: "Fiction in verse", description: "Sunt optio aut id. Commodi dicta provident. Qui expedita vitae quos. Et soluta praesentium. Accusamus impedit aut et omnis temporibus minus.", rating: "2", quote: "Toto, I've got a feeling we're not in Kansas anymore."},
#   {title: "Schindler's List", year: "1993", director: "Hansen Inc", image: "https://ia.media-imdb.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY1000_CR0,0,666,1000_AL_.jpg", genre: "Suspense/Thriller", description: "Quos velit provident ea. Voluptatem repudiandae omnis fugiat. Id totam fugiat qui enim non. Ipsum ut sed. Aut harum est quis impedit quia voluptatem saepe. Aliquam eveniet ipsum quisquam dolores sit ad illo. Corporis eum aut laudantium quam incidunt dolorem voluptatem.", rating: "6", quote: "May the Force be with you."},
#   {title: "Goodfellas", year: "1990", director: "Grady, Bartell and Shields", image: "https://ia.media-imdb.com/images/M/MV5BNThjMzczMjctZmIwOC00NTQ4LWJhZWItZDdhNTk5ZTdiMWFlXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SY1000_CR0,0,669,1000_AL_.jpg", genre: "Crime/Detective", description: "Doloribus ipsam id ut voluptatem autem sed. Amet unde perspiciatis. Enim facere nesciunt est reprehenderit a sequi dolores. Reiciendis laudantium ex eum impedit quibusdam id corporis. Quis ut molestias. Veritatis maiores doloribus nulla.", rating: "8", quote: "I'm going to make him an offer he can't refuse."},
#   {title: "Forrest Gump", year: "1994", director: "Hyatt-Kilback", image: "https://ia.media-imdb.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg", genre: "Biography/Autobiography", description: "Adipisci veniam nulla corrupti odit nobis sit cupiditate. Eveniet at quam sequi iste voluptatem. Et dolores quae nemo aut totam quis. Et sequi aspernatur maiores sapiente voluptas culpa rerum.", rating: "3", quote: "Go ahead, make my day."}
# ])
